POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVmYmEzYmE4MTcxOTcyMGEwY2Q0MmFhNSIsImlhdCI6MTYwNjA0MjU3Mn0.I09n2Y9CrpDYla6D8Vi5GloWtvbEVafJAuBfefi9N3w

{
    "title": "I am Roottoor",
    "author": "RootRootRootRootRoot",
    "url": "root.me",
    "likes": 100
}

# It is only possible if a valid token is sent with the HTTP POST request. 
# The user identified by the token is designated as the creator of the blog.